version: '3'

vars:
  APP_NAME: "todo"
  DOCKER_REGISTRY: "mxssl"
  GO111MODULE: "on"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD
  GIT_TAG:
    sh: git describe --tags --abbrev=0

tasks:
  swagger-validate:
    desc: Validate swagger file
    cmds:
      - swagger validate ./swagger.yml

  swagger-generate:
    desc: Generate server based on a swagger file
    cmds:
      - swagger generate server -A todo -f ./swagger.yml

  run:
    desc: Run server for development
    cmds:
      - go run cmd/todo-server/main.go --port 8080

  dc-build:
    desc: Run docker-compose build
    cmds:
      - docker-compose build

  dc-up:
    desc: Run docker-compose up
    cmds:
      - docker-compose up

  swagger:
    desc: Run docker-compose up swagger
    cmds:
      - docker-compose up swagger

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run
      - gocritic check ./...
      - yamllint .
      - hadolint Dockerfile

  docker-lint:
    desc: Run linters in docker containers
    cmds:
      - |
        docker \
          run \
          --rm \
          -v $(pwd)/Dockerfile:/Dockerfile \
          replicated/dockerfilelint:f7bdc89 \
          /Dockerfile
      - |
        docker \
          run \
          --rm \
          -v $(pwd)/.hadolint.yaml:/.hadolint.yaml \
          -i hadolint/hadolint:v1.18.2 < Dockerfile

  github-release-dry:
    desc: Goreleaser test
    cmds:
      - echo "TAG - {{ .GIT_TAG }}"
      - goreleaser release --rm-dist --snapshot --skip-publish

  github-release:
    desc: Goreleaser
    cmds:
      - echo "TAG - {{ .GIT_TAG }}"
      - goreleaser release --rm-dist

  docker-release:
    desc: Build and push docker image
    cmds:
      - echo "Registry - {{ .DOCKER_REGISTRY }}"
      - echo "TAG - {{ .GIT_TAG }}"
      - docker build --tag {{ .DOCKER_REGISTRY }}/{{ .APP_NAME  }}:{{ .GIT_TAG }} .
      - docker push {{ .DOCKER_REGISTRY }}/{{ .APP_NAME  }}:{{ .GIT_TAG }}
