// Code generated by go-swagger; DO NOT EDIT.

// Package restapi todo app
//
//  My example of a todo app
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
